<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2020/10/04 10:08:13

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=firstproject',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
